from parlai_internal.scripts.train_model import TrainModel
from parlai_internal.scripts.multiprocessing_train import MultiProcessTrain

if __name__ == '__main__':
    # MultiProcessTrain.main(
    TrainModel.main(
        task='wizard_of_wikipedia:generator',
        evaltask='wizard_of_wikipedia:generator:random_split,wizard_of_wikipedia:generator:topic_split',
        aggregate_micro=True,
        model='internal:trans_ikg_bert/trans_ikg',
        model_file='./outputs/TransIKG_wow_bert/model',
        delimiter='[SEP]',
        dict_lower=True,
        variant='bart',
        activation='gelu',
        n_layers=5,
        n_heads=4,
        dropout=0.20,
        relu_dropout=0.20,
        attention_dropout=0.20,
        ffn_size=1024,
        embedding_size=768,
        log_every_n_steps=500,
        validation_patience=20,
        validation_metric='ppl',
        validation_metric_mode='min',
        validation_every_n_epochs=1,
        save_after_valid=True,
        n_positions=128,
        truncate=128,
        max_knowledge=32,
        knowledge_alpha=1.0,
        knowledge_truncate=32,
        learningrate=1e-4,
        warmup_updates=5000,
        learn_positional_embeddings=True,
        auxiliary_loss=True,
        fusion_attn='mlp',
        history_size=8,
        clip=0.1,
        optimizer='adam',
        lr_scheduler='invsqrt',
        metrics='all',
        skip_generation=False,
        batchsize=32,
        # update_freq=4,
        inference='beam',
        beam_size=2,
        beam_block_ngram=3,
        label_smoothing=True,
        use_dialogue_position=True,
        use_correlation_integration=True,
        use_overall_integration=True,
        use_copy=True,
        gpu=0,
        add_missing_turns='all',
    )